import os
print("Добро пожаловать в инструмент для управления архивами 507-zip! от 507-team")
print("")
print("Выберите действие:")
print("1: Разархивировать архив")
print("")
choice = input()
if choice == "1":
    print("Выберите тип архива")
    print("1: ZIP")
    print("2: TAR (Пока что не работает)")
    print("")
    print("(Что бы узнать тип архива посмотрите на конец файла .tar это TAR .zip это ZIP)")
    print("")
    tiparchiveforextract = input()
    if tiparchiveforextract == "1":
        print("Наишите название файла архива:")
        print("ВНИМАНИЕ!: ПОСЛЕ ЭТОГО ЕСЛИ В АРХИВЕ БЫЛИ ФАЙЛЫ КОТОРЫЕ НАЗЫВАЛИСЬ ТАКЖЕ КАК И В ЭТОЙ ДИРЕКТОРИИ ОНИ БУДУТ ПЕРЕЗАПИСАНЫ!")
        namearchiveforextract = input()
        print("")
        print("Список файлов в архиве:")
        print("------------------------------------------------------")
        os.system("unzip -l " + namearchiveforextract)
        print("------------------------------------------------------")
        print("")
        print("И последнее... Создать подпапку? Y/N")
        cozdatpodpapkyforextract = input()
        podpapkaforextract = namearchiveforextract.replace(".zip", "")
        
        if cozdatpodpapkyforextract == "y":
            print("Создаю...")
            os.system("mkdir " + podpapkaforextract)
            print("Папка создана!")
            print("Распаковываю....")
            os.system("unzip -o -q " + namearchiveforextract + " -d " + podpapkaforextract)
            print("Распаковка завершена!")
            print("")
            print("--------------------------------------------------------")
            print("Список файлов/каталогов:")
            os.system("dir " + podpapkaforextract)
            print("--------------------------------------------------------")
            print("")
            print("Удачи!")
